server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka的服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/userCharley/springcloud-config.git #Gitee上面的仓库地址
          search-paths: #搜索目录
            - springcloud-config
      label: master #读取分支

  #RabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册进Eureka
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
